export { default as Home } from './home.page'
export { default as Login } from './login.page'
export { default as PageNotFound } from './page-not-found'
export { default as Pricing } from './pricing.page'
export { default as Product } from './product.page'
